swagger: '2.0'
info:
  title: Trade Alert API Gateway
  description: API Gateway for Trade Alert Service
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-endpoints:
  - name: tradealert-api.poe2.com
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
security:
  - api_key: []
paths:
  /_health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      x-google-backend:
        address: ${service_uri}/_health
      responses:
        '200':
          description: Service is healthy
          schema:
            type: object
            properties:
              uptime:
                type: number
              timestamp:
                type: number
              discord:
                type: boolean
        '503':
          description: Service is unhealthy
  
  /auth:
    get:
      summary: Discord OAuth2 authorization URL
      operationId: getAuthUrl
      x-google-backend:
        address: ${service_uri}/auth
      parameters:
        - name: redirect_uri
          in: query
          required: true
          type: string
        - name: NL_TOKEN
          in: query
          required: true
          type: string
      responses:
        '200':
          description: Authorization URL generated
          schema:
            type: object
            properties:
              url:
                type: string
        '400':
          description: Bad request
  
  /auth/callback:
    get:
      summary: Discord OAuth2 callback
      operationId: authCallback
      x-google-backend:
        address: ${service_uri}/auth/callback
      parameters:
        - name: code
          in: query
          type: string
        - name: state
          in: query
          type: string
      responses:
        '302':
          description: Redirect to client with auth data
        '400':
          description: Invalid request
  
  /auth/refresh:
    post:
      summary: Refresh Discord access token
      operationId: refreshToken
      x-google-backend:
        address: ${service_uri}/auth/refresh
      parameters:
        - name: refresh_token
          in: body
          required: true
          schema:
            type: object
            properties:
              refresh_token:
                type: string
      responses:
        '200':
          description: New tokens generated
          schema:
            type: object
            properties:
              access_token:
                type: string
              refresh_token:
                type: string
              expires_in:
                type: number
        '400':
          description: No refresh token provided
        '401':
          description: Invalid refresh token
  
  /api/trade-alert:
    post:
      summary: Send trade alert to Discord
      operationId: sendTradeAlert
      security:
        - api_key: []
      x-google-backend:
        address: ${service_uri}/api/trade-alert
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              player:
                type: string
              message:
                type: string
            required:
              - player
              - message
      responses:
        '200':
          description: Alert sent successfully
        '400':
          description: Missing required fields
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

x-google-management:
  metrics:
    - name: "requests"
      displayName: "Requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "requests-per-project"
        metric: "requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 1000
  security:
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      allowHeaders:
        - x-api-key
        - Content-Type
      maxAge: 3600 